trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /practice/lab11.yaml
pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  jobs:
  - job: DevJob1
    displayName: First Job
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo Dev stage1
        displayName: step1
      - script: echo Dev stage2
        displayName: step2

  - job: DevJob2
    displayName: Second Job
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo Dev stage1
        displayName: step1
      - script: echo Dev stage2
        displayName: step2
      
- stage: QA
  dependsOn: Dev
  condition: succeeded('Dev')
  jobs:
  - job: QAJob1
    displayName: QA
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo QA stage1
        displayName: QA stage1
      - script: echo QA stage1
        displayName: QA stage1

  - job: QA_Job2
    displayName: QA
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo QA stage1
        displayName: QA stage1
      - script: echo QA stage2
        displayName: QA stage2

- stage: UAT
  dependsOn: QA failed
  condition: unsucceeded('QA')
  jobs:
  - job: UATJob1
    displayName: UAT
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo UAT stage1
        displayName: UAT stage1
      - script: echo UAT stage2
        displayName: UAT stage2
  - job: UATJob_2
    displayName: UAT 2
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo UAT stage1
        displayName: UAT stage1
      - script: echo UAT stage2
        displayName: UAT stage2        

- stage: Preprod
  dependsOn: none
  jobs:
  - job: PreprodJob1
    displayName: Preprod
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo preprod stage1
        displayName: Preprod stage1
      - script: echo Preprod stage1
        displayName: Preprod stage1  

  - job: PreprodJob2
    displayName: Preprod
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo Preprod stage1
        displayName: Preprod stage1
      - script: echo Preprod stage1
        displayName: Preprod stage1        

- stage: Production
  dependsOn: UAT
  condition: failed()
  jobs:
  - job: ProductionJob1
    displayName: Preprod
    continueOnError: true
    workspace:
      clean: outputs
    steps:
      - script: echo Production stage1
        displayName: production stage1
      - script: echo Production stage2
        displayName: production stage2  
