trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /practice/lap1.yaml
pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  jobs:
  - job: DevJob
    steps:
      - script: echo "Dev stage"

- stage: QA
  dependsOn: Dev
  jobs:
  - job: QAJob
    steps:
      - script: echo "QA stage"

- stage: UAT
  dependsOn: QA
  jobs:
  - job: UATJob
    steps:
      - script: echo "UAT stage"

- stage: Preprod
  jobs:
  - job: PreprodJob
    steps:
      - script: echo "Preprod stage"

- stage: Production
  dependsOn: UAT
  condition: failed()
  jobs:
  - job: ProductionJob
    steps:
      - script: echo "Production stage"
