trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /practice/variable_lap_2/main-variable.yaml

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job: FirstJob
    variables:
     - template: /practice/variable_lap_2/variable_template.yaml

    steps:
    - script: echo $(my_var) ${{ variables.var1 }} ${{ variables.var2 }} ${{ variables.var3 }}