trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /loop/main.yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: Stage
  jobs:
   - template: /loop/loop.yaml
     parameters:
       loop_values: 
       - "umair"
       - "value2"
       - "value3"